/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author nestorojeda
 */
public class ImagePanel extends javax.swing.JPanel {
    private BufferedImage img;
    private boolean loaded = false;

    public ImagePanel(){
        initComponents();
     }

       @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(!loaded)g.drawImage(img, 0, 0, this);
        else g.drawImage(img, 0, 0,img.getWidth(), img.getHeight(), this);
        
        
    }

   
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void setImage(BufferedImage img){
        this.img = img;
        this.repaint();
        
    }
    
    void setImage(File file) {
        try{
            img =  ImageIO.read(file);
            this.setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
            loaded = true;
          
        } catch (Exception e){
            System.out.print(e);
        }
        this.repaint();
    }
   
    
    
    int getImageWidth(){
        return img.getWidth();
    }
    
    int getImageHeight(){
        return img.getHeight();
    }
    
    
    BufferedImage getImage(){
        return img;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
